### PR TITLE
Let's see if atlantis is working

### PR DESCRIPTION
**Pull request by ewilde**
Signed-off-by: Edward Wilde <ewilde@gmail.com>

### CODE REVIEW

**Comment by jeeves-ewilde** [comment]
Ran Plan for dir: `github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ github_branch_protection.doc
      id:                                                         <computed>
      branch:                                                     "master"
      enforce_admins:                                             "false"
      etag:                                                       <computed>
      repository:                                                 "${github_repository.documentation.id}"
      required_pull_request_reviews.#:                            "1"
      required_pull_request_reviews.0.dismiss_stale_reviews:      "false"
      required_pull_request_reviews.0.require_code_owner_reviews: "true"

+ github_repository.documentation
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             "master"
      description:                                                "company wide awesome documentation"
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "documentation"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_repository.goto_terraform
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             <computed>
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "goto-terraform"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_repository.website
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             <computed>
      description:                                                "The 12factor.io public website"
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      has_downloads:                                              "true"
      has_issues:                                                 "true"
      has_wiki:                                                   "true"
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "12factor.io"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_team.ci
      id:                                                         <computed>
      description:                                                "Members of this team manage content within the organisation i.e. documentation, the website ..."
      etag:                                                       <computed>
      name:                                                       "CI"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team.content
      id:                                                         <computed>
      description:                                                "Members of this team manage content within the organisation i.e. documentation, the website ..."
      etag:                                                       <computed>
      name:                                                       "Content"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team.content_code_owners
      id:                                                         <computed>
      description:                                                "Members of this team have permissions to approve pull requests for the content team"
      etag:                                                       <computed>
      name:                                                       "Approvers"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team_membership.ci_team_membership
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.ci.id}"
      username:                                                   "jeeves-ewilde"

+ github_team_membership.content_team_membership[0]
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.content.id}"
      username:                                                   "bob-ewilde"

+ github_team_membership.content_team_membership[1]
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.content.id}"
      username:                                                   "sally-ewilde"

+ github_team_repository.team_repo_documentation
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "documentation"
      team_id:                                                    "${github_team.content.id}"

+ github_team_repository.team_repo_goto_terraform
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "goto-terraform"
      team_id:                                                    "${github_team.ci.id}"

+ github_team_repository.team_repo_webiste
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "12factor.io"
      team_id:                                                    "${github_team.content.id}"
Plan: 13 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d github`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-ed.ngrok.io/lock?id=12factor-io%252Fgoto-terraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ewilde** [comment]
atlantis plan

**Comment by jeeves-ewilde** [comment]
Ran Plan for dir: `github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ github_branch_protection.doc
      id:                                                         <computed>
      branch:                                                     "master"
      enforce_admins:                                             "false"
      etag:                                                       <computed>
      repository:                                                 "${github_repository.documentation.id}"
      required_pull_request_reviews.#:                            "1"
      required_pull_request_reviews.0.dismiss_stale_reviews:      "false"
      required_pull_request_reviews.0.require_code_owner_reviews: "true"

+ github_repository.documentation
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             "master"
      description:                                                "company wide awesome documentation"
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "documentation"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_repository.goto_terraform
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             <computed>
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "goto-terraform"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_repository.website
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             <computed>
      description:                                                "The 12factor.io public website"
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      has_downloads:                                              "true"
      has_issues:                                                 "true"
      has_wiki:                                                   "true"
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "12factor.io"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_team.ci
      id:                                                         <computed>
      description:                                                "Members of this team manage content within the organisation i.e. documentation, the website ..."
      etag:                                                       <computed>
      name:                                                       "CI"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team.content
      id:                                                         <computed>
      description:                                                "Members of this team manage content within the organisation i.e. documentation, the website ..."
      etag:                                                       <computed>
      name:                                                       "Content"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team.content_code_owners
      id:                                                         <computed>
      description:                                                "Members of this team have permissions to approve pull requests for the content team"
      etag:                                                       <computed>
      name:                                                       "Approvers"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team_membership.ci_team_membership
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.ci.id}"
      username:                                                   "jeeves-ewilde"

+ github_team_membership.content_team_membership[0]
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.content.id}"
      username:                                                   "bob-ewilde"

+ github_team_membership.content_team_membership[1]
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.content.id}"
      username:                                                   "sally-ewilde"

+ github_team_repository.team_repo_documentation
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "documentation"
      team_id:                                                    "${github_team.content.id}"

+ github_team_repository.team_repo_goto_terraform
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "goto-terraform"
      team_id:                                                    "${github_team.ci.id}"

+ github_team_repository.team_repo_webiste
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "12factor.io"
      team_id:                                                    "${github_team.content.id}"
Plan: 13 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d github`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-ed.ngrok.io/lock?id=12factor-io%252Fgoto-terraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ewilde** [comment]
atlantis help

**Comment by jeeves-ewilde** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan   Runs 'terraform plan' for the changes in this pull request.
         To plan a specific project, use the -d, -w and -p flags.
  apply  Runs 'terraform apply' on all unapplied plans from this pull request.
         To only apply a specific plan, use the -d, -w and -p flags.
  help   View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.

**Comment by ewilde** [comment]
atlantis plan

**Comment by jeeves-form3-oss** [comment]
Ran Plan for dir: `github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ github_branch_protection.doc
      id:                                                         <computed>
      branch:                                                     "master"
      enforce_admins:                                             "false"
      etag:                                                       <computed>
      repository:                                                 "${github_repository.documentation.id}"
      required_pull_request_reviews.#:                            "1"
      required_pull_request_reviews.0.dismiss_stale_reviews:      "false"
      required_pull_request_reviews.0.require_code_owner_reviews: "true"

+ github_repository.documentation
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             "master"
      description:                                                "company wide awesome documentation"
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "documentation"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_repository.goto_terraform
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             <computed>
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "goto-terraform"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_repository.website
      id:                                                         <computed>
      allow_merge_commit:                                         "true"
      allow_rebase_merge:                                         "true"
      allow_squash_merge:                                         "true"
      archived:                                                   "false"
      default_branch:                                             <computed>
      description:                                                "The 12factor.io public website"
      etag:                                                       <computed>
      full_name:                                                  <computed>
      git_clone_url:                                              <computed>
      has_downloads:                                              "true"
      has_issues:                                                 "true"
      has_wiki:                                                   "true"
      html_url:                                                   <computed>
      http_clone_url:                                             <computed>
      name:                                                       "12factor.io"
      ssh_clone_url:                                              <computed>
      svn_url:                                                    <computed>

+ github_team.ci
      id:                                                         <computed>
      description:                                                "Members of this team manage content within the organisation i.e. documentation, the website ..."
      etag:                                                       <computed>
      name:                                                       "CI"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team.content
      id:                                                         <computed>
      description:                                                "Members of this team manage content within the organisation i.e. documentation, the website ..."
      etag:                                                       <computed>
      name:                                                       "Content"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team.content_code_owners
      id:                                                         <computed>
      description:                                                "Members of this team have permissions to approve pull requests for the content team"
      etag:                                                       <computed>
      name:                                                       "Approvers"
      privacy:                                                    "secret"
      slug:                                                       <computed>

+ github_team_membership.ci_team_membership
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.ci.id}"
      username:                                                   "jeeves-ewilde"

+ github_team_membership.content_team_membership[0]
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.content.id}"
      username:                                                   "bob-ewilde"

+ github_team_membership.content_team_membership[1]
      id:                                                         <computed>
      etag:                                                       <computed>
      role:                                                       "member"
      team_id:                                                    "${github_team.content.id}"
      username:                                                   "sally-ewilde"

+ github_team_repository.team_repo_documentation
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "documentation"
      team_id:                                                    "${github_team.content.id}"

+ github_team_repository.team_repo_goto_terraform
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "goto-terraform"
      team_id:                                                    "${github_team.ci.id}"

+ github_team_repository.team_repo_webiste
      id:                                                         <computed>
      etag:                                                       <computed>
      permission:                                                 "push"
      repository:                                                 "12factor.io"
      team_id:                                                    "${github_team.content.id}"
Plan: 13 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d github`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-ed.ngrok.io/lock?id=12factor-io%252Fgoto-terraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jeeves-form3-oss** [comment]
Ran Plan for dir: `github` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d github`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-ed.ngrok.io/lock?id=12factor-io%252Fgoto-terraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d github`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ewilde** [comment]
atlantis apply

**Comment by jeeves-form3-oss** [comment]
Ran Apply for dir: `github` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

**Comment by jeeves-form3-oss** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `github` workspace: `default`

**Pull request merged**
